CREATE TABLE LOCATION (
    CITY VARCHAR(20),
    PINCODE INT PRIMARY KEY,
    STATE VARCHAR(30)
);

INSERT INTO LOCATION VALUES ('Junagadh',362001,'Gujarat');
INSERT INTO LOCATION VALUES ('Ahmedabad',380001,'Gujarat');
INSERT INTO LOCATION VALUES ('Lucknow',226001,'UP');
INSERT INTO LOCATION VALUES ('Warangal',506002,'Telangana');
INSERT INTO LOCATION VALUES ('Rajkot',360001,'Gujarat');
INSERT INTO LOCATION VALUES ('Kota',324006,'Rajasthan');
INSERT INTO LOCATION VALUES ('Jaipur',302003,'Rajasthan');
INSERT INTO LOCATION VALUES ('Delhi',110001,'Delhi');
INSERT INTO LOCATION VALUES ('NewMumbai',410206,'Maharashtra');
INSERT INTO LOCATION VALUES ('Hyderabad',500005,'Telangana');
