CREATE TABLE HOSPITAL (
    NAME VARCHAR(50),
    HOSPITAL_ID NUMBER PRIMARY KEY,
    PINCODE NUMBER,
    FOREIGN KEY (PINCODE) REFERENCES LOCATION(PINCODE)
);

INSERT INTO HOSPITAL VALUES('Walkhart',202,360001);
INSERT INTO HOSPITAL VALUES('Milestone',203,600002);
INSERT INTO HOSPITAL VALUES('Newlife',301,560002);