CREATE TABLE VACCINATION_CENTER (
    CENTER_ID VARCHAR(10) PRIMARY KEY,
    AREA VARCHAR(100),
    PINCODE NUMBER,
    FOREIGN KEY (PINCODE) REFERENCES LOCATION(PINCODE)
);

INSERT INTO VACCINATION_CENTER VALUES('C1301','Laxmi Nagar Soc.',362001);
INSERT INTO VACCINATION_CENTER VALUES('C1302','Talav Street',362001);
INSERT INTO VACCINATION_CENTER VALUES('C1303','Railway Station',362001);