CREATE TABLE SUPPLIES (
    SUPPLIER_ID NUMBER,
    HOSPITAL_ID NUMBER,
    PRIMARY KEY (SUPPLIER_ID, HOSPITAL_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(ID),
    FOREIGN KEY (HOSPITAL_ID) REFERENCES HOSPITAL(HOSPITAL_ID)
);

INSERT INTO SUPPLIES VALUES(6327274,202);
INSERT INTO SUPPLIES VALUES(4921885,203);