-- ANALYTICS.SQL :: IMMUNITRACKDB --

-- 1. City with the highest number of vaccinations
SELECT L.CITY, COUNT(*) AS total_vaccinations
FROM VACCINATION_RECORD VR
JOIN CITIZENS C ON VR.AADHAR_NUMBER = C.AADHAR_NUMBER
JOIN LOCATION L ON C.PINCODE = L.PINCODE
GROUP BY L.CITY
ORDER BY total_vaccinations DESC
FETCH FIRST 1 ROWS ONLY;

-- 2. Most common age group among vaccinated individuals
SELECT AGE, COUNT(*) AS count
FROM VACCINATION_RECORD
GROUP BY AGE
ORDER BY count DESC
FETCH FIRST 1 ROWS ONLY;

-- 3. Worker(s) who vaccinated the most people
SELECT HW.WORKER_ID, HW.POST, H.NAME AS HOSPITAL_NAME, COUNT(*) AS total
FROM VACCINATION_RECORD VR
JOIN HEALTH_WORKERS HW ON VR.WORKER_ID = HW.WORKER_ID
JOIN HOSPITAL H ON HW.HOSPITAL_ID = H.HOSPITAL_ID
GROUP BY HW.WORKER_ID, HW.POST, H.NAME
ORDER BY total DESC
FETCH FIRST 1 ROWS ONLY;

-- 4. Country with the highest number of vaccine exports
SELECT E.RECEIVER AS COUNTRY, SUM(E.QUANTITY) AS total_exported
FROM EXPORT E
GROUP BY E.RECEIVER
ORDER BY total_exported DESC
FETCH FIRST 1 ROWS ONLY;

-- 5. Total vaccine exports per country
SELECT E.RECEIVER AS COUNTRY, SUM(E.QUANTITY) AS total_exported
FROM EXPORT E
GROUP BY E.RECEIVER
ORDER BY total_exported DESC;

-- 6. Hospital with the highest number of workers
SELECT H.NAME, COUNT(*) AS worker_count
FROM HEALTH_WORKERS HW
JOIN HOSPITAL H ON HW.HOSPITAL_ID = H.HOSPITAL_ID
GROUP BY H.NAME
ORDER BY worker_count DESC
FETCH FIRST 1 ROWS ONLY;

-- 7. Most senior health worker (oldest DOB)
SELECT C.FNAME, C.LNAME, C.DOB, L.CITY
FROM HEALTH_WORKERS HW
JOIN CITIZENS C ON HW.AADHAR_NUMBER = C.AADHAR_NUMBER
JOIN LOCATION L ON C.PINCODE = L.PINCODE
ORDER BY C.DOB ASC
FETCH FIRST 1 ROWS ONLY;

-- 8. Vaccination center with the most number of visits
SELECT VC.CENTER_ID, VC.AREA, COUNT(*) AS total_visits
FROM VACCINATION_RECORD VR
JOIN VACCINATION_CENTER VC ON VR.CENTER_ID = VC.CENTER_ID
GROUP BY VC.CENTER_ID, VC.AREA
ORDER BY total_visits DESC
FETCH FIRST 1 ROWS ONLY;

-- 9. Number of vaccinations per vaccine type
SELECT V.NAME, COUNT(*) AS total_given
FROM VACCINATION_RECORD VR
JOIN VACCINE V ON VR.VACCINE_ID = V.VACCINE_ID
GROUP BY V.NAME
ORDER BY total_given DESC;

-- 10. Monthly vaccination trend
SELECT EXTRACT(MONTH FROM DATETIME) AS month, COUNT(*) AS count
FROM VACCINATION_RECORD
GROUP BY EXTRACT(MONTH FROM DATETIME)
ORDER BY month;

-- 11. Number of unique citizens vaccinated
SELECT COUNT(DISTINCT AADHAR_NUMBER) AS unique_citizens
FROM VACCINATION_RECORD;

-- 12. Vaccines exported by each supplier
SELECT S.NAME AS SUPPLIER_NAME, COUNT(DISTINCT E.VACCINE_ID) AS total_exported_types
FROM EXPORT E
JOIN VACCINE V ON E.VACCINE_ID = V.VACCINE_ID
JOIN SUPPLIERS S ON V.SUPPLIER_ID = S.ID
GROUP BY S.NAME
ORDER BY total_exported_types DESC;
